### ISSUE TITLE
Do not try to trivially write to storage

### ISSUE THREAD

**Issue by shawntabrizi** [JoshOrndorff/TicTacToe#1]
https://github.com/JoshOrndorff/TicTacToe/blob/b10c7125435ff0c11fb132cf92be159a1d2d096c/runtime/src/tictactoe.rs#L78

Writing to storage is a cost to the blockchain. A pretty heavy one at that. Trying to trivially write to storage (when you already know the default value and stuff) is bad practice

**Comment by JoshOrndorff** [comment]
That code is removed in 3c7a2cd7c6c78d2dfde60127
