### ISSUE TITLE
possible race condition

### ISSUE THREAD

**Issue by shawntabrizi** [JoshOrndorff/TicTacToe#5]
User can "win" the game, but then another user is not blocked from playing another spot and also winning the game.

Then they could claim the win before the other user does.

Imagine a block producer who ignores transactions from one user...

May or may not be a real issue, would need to think about it more

**Comment by JoshOrndorff** [comment]
Oh great point. We definitely don't want other players to continue making moves after the game is won. But we also don't want the expensive win-searching to happen on-chain after every move. I'm thinking the best solution is to remove `claim_win` and replace it with `move_and_win` where a player takes a final move and simultaneously claims the win. That would simplify the frontend code too tbh.

**Comment by shawntabrizi** [comment]
That sounds like a very reasonable solution

**Comment by JoshOrndorff** [comment]
Fixed in a8873da6a6fc0d6b34c356ad6586ea8a2ab6ab4d
